export {
  COMPANY_STATUSES,
  DEPLOYMENT_MODES,
  DEPLOYMENT_EXPOSURES,
  AUTH_BASE_URL_MODES,
  ISSUE_STATUSES,
  ISSUE_PRIORITIES,
  GOAL_LEVELS,
  GOAL_STATUSES,
  PROJECT_STATUSES,
  PROJECT_COLORS,
  type CompanyStatus,
  type DeploymentMode,
  type DeploymentExposure,
  type AuthBaseUrlMode,
  type IssueStatus,
  type IssuePriority,
  type GoalLevel,
  type GoalStatus,
  type ProjectStatus,
} from "./constants.js";

export type {
  Company,
  AssetImage,
  Project,
  ProjectGoalRef,
  Issue,
  IssueAssigneeAdapterOverrides,
  IssueComment,
  IssueAttachment,
  IssueLabel,
  Goal,
  DashboardSummary,
  ActivityEvent,
  Document,
} from "./types/index.js";

export {
  createCompanySchema,
  updateCompanySchema,
  type CreateCompany,
  type UpdateCompany,
  createProjectSchema,
  updateProjectSchema,
  createProjectWorkspaceSchema,
  updateProjectWorkspaceSchema,
  projectExecutionWorkspacePolicySchema,
  type CreateProject,
  type UpdateProject,
  type CreateProjectWorkspace,
  type UpdateProjectWorkspace,
  type ProjectExecutionWorkspacePolicy,
  createIssueSchema,
  createIssueLabelSchema,
  updateIssueSchema,
  issueExecutionWorkspaceSettingsSchema,
  checkoutIssueSchema,
  addIssueCommentSchema,
  linkIssueApprovalSchema,
  createIssueAttachmentMetadataSchema,
  type CreateIssue,
  type CreateIssueLabel,
  type UpdateIssue,
  type IssueExecutionWorkspaceSettings,
  type CheckoutIssue,
  type AddIssueComment,
  type LinkIssueApproval,
  type CreateIssueAttachmentMetadata,
  createGoalSchema,
  updateGoalSchema,
  type CreateGoal,
  type UpdateGoal,
  createAssetImageMetadataSchema,
  type CreateAssetImageMetadata,
  createDocumentSchema,
  updateDocumentSchema,
  type CreateDocument,
  type UpdateDocument,
} from "./validators/index.js";

export type { BlockDefinition, BlockNavItem, BlockNavSection } from "./block-types.js";

export { API_PREFIX, API } from "./api.js";
export { deriveProjectUrlKey, normalizeProjectUrlKey } from "./project-url-key.js";
export {
  PROJECT_MENTION_SCHEME,
  buildProjectMentionHref,
  parseProjectMentionHref,
  extractProjectMentionIds,
  type ParsedProjectMention,
} from "./project-mentions.js";
